services:
  cc.apps.controller:
    class: thechristiancrew\apps\controller\main_controller
    arguments:
      - @config
      - @controller.helper
      - @template
      - @user
      - @request
      - %core.root_path%
